### PR TITLE
fix(is/tabbable): add element types email and number in IOS

### PR DESCRIPTION
**Pull request by davydof**
Add element types `email` and `number` in IOS

### CODE REVIEW

**Comment by davydof** [comment]
@marcysutton @rodneyrehm 
friendly ping guys

**Comment by rodneyrehm** [comment]
Hey there! Interesting find. Here I was thinking we had covered all elements, but obviously we forgot about all the "new" input types. I've added those locally and ran the tests in browsers available to me at the moment:

localhost_5000_web_data-tables_focusable

The build infrastructure seems to have broken down since our last commit (3 years ago) and I'm currently lacking the time to resurrect this stuff.

**Comment by davydof** [comment]
@rodneyrehm very very friendly ping :)

**Comment by davydof** [comment]
@rodneyrehm
any progress after 3 years? :)

**Comment by davydof** [comment]
@medialize
@jayzelenkov
@rodneyrehm
@varemenos
anyone? :)

**Pull request closed without merging**
