### PR TITLE
fixes #126

### LINKED ISSUE #126: document.write() not available in Chrome packaged apps

### PR DESCRIPTION
**Pull request by ryan-ludwig**

### CODE REVIEW

**Comment by rodneyrehm** [comment]
It's not necessary to open issue and PR separately, unless the issue itself is in need of discussion.

Please rebase this branch against `upstream/master` so that the PR only contains the commit 35f6cdf, and not all of those merge commits.

**Comment by rodneyrehm** [comment]
link #126

**Comment by ryan-ludwig** [comment]
Sorry Rodney, pretty new to Github. Working on getting you a clean pull request.

**Comment by rodneyrehm** [comment]
> Sorry Rodney, pretty new to Github.

no worries… it's not like I know what I'm doing, either ;)

> Working on getting you a clean pull request.

If you guys want to continue contributing changes (which I'd much appreciate!), I'd suggest you throw away your `origin/master` and start new from `upstream/master`. And then keep that branch clean (i.e. don't `git merge upstream/master` as suggested by [syncing a fork](https://help.github.com/articles/syncing-a-fork/), but `git rebase upstream/master` instead). Otherwise branch off `upstream/master` (after running a `git fetch upstream`) for your PRs.

**Pull request closed without merging**
