### PR TITLE
fix(util/platform): Protect against null value before attempting .slice()

### PR DESCRIPTION
**Pull request by jordanaustin**

### CODE REVIEW

**Comment by rodneyrehm** [comment]
Don't worry about the failing tests… BrowserStack's Safari isn't playing nice today…

**Comment by rodneyrehm** [comment]
great! can you squash the commits and force push? then I'd merge that asap :)

**Comment by jordanaustin** [comment]
Shoot, I just messed up this squash. Gimme a minute to fix it.

**Comment by jordanaustin** [comment]
My brain wasn't awake yet. This should be good.

**Comment by rodneyrehm** [comment]
Thx!

**Pull request merged**
