### PR TITLE
Issue/110 observe shadows

### PR DESCRIPTION
**Pull request by rodneyrehm**
covers #110 - cc @jordanaustin

### CODE REVIEW

**Comment by jordanaustin** [comment]
Nice work @rodneyrehm. Is this the final issue for 1.1.0?

**Comment by rodneyrehm** [comment]
nope, the [1.1.0 milestone](https://github.com/medialize/ally.js/milestones/1.1.0%20-%20second%20wave) shows one more issue - but that's an arbitrary goal. I'll probably just move the remaining issue to 1.2.0 (and *stop* creating huge releases like this...)

**Comment by jordanaustin** [comment]
I like that plan :+1:

**Comment by jordanaustin** [comment]
@rodneyrehm just to get a general idea, what do you think the time frame for 1.1.0 is?

**Comment by rodneyrehm** [comment]
> just to get a general idea, what do you think the time frame for 1.1.0 is?

There's just one issue left on the roadmap. Some cleanups and tests. 2 weeks should do it, so it's likely happening before you go hunting easter eggs :)

**Comment by jordanaustin** [comment]
Wow, fast reply! thanks @rodneyrehm

**Pull request merged**
