### PR TITLE
fix(supports.focus-in-hidden-iframe): append element instead of document write

### PR DESCRIPTION
**Pull request by ryan-ludwig**
covers #126

### CODE REVIEW

**Comment by rodneyrehm** [comment]
The tests are failing for this branch, but pass when kicked off locally. No idea what's wrong here… I pushed [pr-128-browserstack](https://github.com/medialize/ally.js/tree/pr-128-browserstack) (only containing your commit) to see if that does anything different…

**Comment by rodneyrehm** [comment]
It appears that you need to close the document before you can safely access `document.body`, as fc44bd3 shows. Do you want to update your PR (please squash the commits) or should I handle this?

**Comment by rodneyrehm** [comment]
I've tried creating a Chrome App that runs the tests from `node_modules/intern/client.html?config=test/browser`, but could not make it actually load and execute the tests. It would be great if this were possible, as we'd otherwise go from issue to issue once they're observed - which may not be the case for features that you simply aren't using.

**Comment by ryan-ludwig** [comment]
Hi Rodney, sorry I'm having a tough time getting a clean rebase. Feel free to close this request and run with fc44bd3 .

**Comment by rodneyrehm** [comment]
merged as 7d18260 - thanks!

**Pull request closed without merging**
